_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.11.7
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 84
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 84
                - 105
            "3":
                - 13
                - 23
                - 55
            "4": 3.11.7
            "5": 0.18.6
            "6": 4.46.2
            "8":
                - 5
            "12": 0.18.6
            "13": darwin-arm64
